### ISSUE TITLE
Missing Exclusive Treasures Pool

### ISSUE THREAD

**Issue by ShrimpMelissa** [ShrimpMelissa/HOCLegends#12]
### Issue: Current pool of treasure doesn't contain old heroes available treasures and current temple ones.

The list of current missing treasures to the treasure box pool are the following: ( Images below to confirm -- BOX I or II doesn't exist
it's all just one BOX! )

**FiX: Include them to the current exclusive treasure selection pool**
- Seductress Whip
- Underworld Strider Lamp
- Sinister Dragoon Cleaver
- Monkey King Armor
- Swordmaster Radiance 
- Blessed Guardian Shield
- Scarlet Velvet Staff
- Nezha's treasure

![image](https://user-images.githubusercontent.com/117372233/204190489-3bda57e9-8c4b-4e31-a461-094e949e2bf9.png)
![image](https://user-images.githubusercontent.com/117372233/204190501-e8d32260-08e2-4afb-9a35-884713e416c9.png)
![image](https://user-images.githubusercontent.com/117372233/204190519-5ed0099d-fe1d-4bfd-9dbd-3f3f24d1b914.png)
![image](https://user-images.githubusercontent.com/117372233/204190718-c3b4d23d-44b7-4802-9d23-1f2394907fef.png)
![image](https://user-images.githubusercontent.com/117372233/204190730-e88bb6de-8735-4939-9942-2e113cb76fce.png)

**Comment by Veya-HOC** [comment]
Actually, the selection crate doesn't guarantee all treasures, only the given treasures, ppl can preview the treasure before buying them.
